import os
import json
import requests
from datetime import datetime, timedelta
from collections import defaultdict

class ProductHuntTracker:
    def __init__(self):
        self.api_token = os.getenv('PRODUCT_HUNT_API_TOKEN')
        self.slack_webhook = os.getenv('SLACK_WEBHOOK_URL')
        self.telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
        self.telegram_chat_id = os.getenv('TELEGRAM_CHAT_ID')
        
        if not self.api_token:
            raise ValueError("PRODUCT_HUNT_API_TOKEN is required")
        
        self.headers = {
            'Authorization': f'Bearer {self.api_token}',
            'Content-Type': 'application/json',
            'Accept': 'application/json'
        }
        self.base_url = 'https://api.producthunt.com/v2/api/graphql'
    
    def fetch_today_posts(self, limit=20):
        query = """
        query {
          posts(featured: true, first: %d) {
            edges {
              node {
                id
                name
                tagline
                description
                url
                votesCount
                commentsCount
                createdAt
                website
                thumbnail { url }
                topics { edges { node { name } } }
                maker { name username }
                user { name username }
              }
            }
          }
        }
        """ % limit
        
        try:
            response = requests.post(
                self.base_url,
                headers=self.headers,
                json={'query': query},
                timeout=30
            )
            response.raise_for_status()
            data = response.json()
            
            if 'errors' in data:
                print(f"API Errors: {data['errors']}")
                return []
            
            posts = []
            for edge in data.get('data', {}).get('posts', {}).get('edges', []):
                node = edge['node']
                posts.append({
                    'name': node.get('name'),
                    'tagline': node.get('tagline'),
                    'url': node.get('url'),
                    'votes': node.get('votesCount', 0),
                    'comments': node.get('commentsCount', 0),
                    'website': node.get('website'),
                    'topics': [t['node']['name'] for t in node.get('topics', {}).get('edges', [])],
                    'maker': node.get('maker', {}).get('name') if node.get('maker') else None,
                    'hunter': node.get('user', {}).get('name') if node.get('user') else None,
                })
            
            return sorted(posts, key=lambda x: x['votes'], reverse=True)
        except Exception as e:
            print(f"Error fetching posts: {e}")
            return []
    
    def analyze_categories(self, posts):
        categories = defaultdict(list)
        for post in posts:
            for topic in post.get('topics', []):
                categories[topic].append(post)
        return dict(sorted(categories.items(), key=lambda x: len(x[1]), reverse=True))
    
    def generate_report(self, posts):
        date_str = datetime.now().strftime('%Y-%m-%d')
        categories = self.analyze_categories(posts)
        
        report = f"""# Product Hunt Daily Report - {date_str}

## Summary
- **Total Products:** {len(posts)}
- **Total Votes:** {sum(p['votes'] for p in posts):,}
- **Total Comments:** {sum(p['comments'] for p in posts):,}

## Top 10 Products

"""
        for i, post in enumerate(posts[:10], 1):
            report += f"""### {i}. {post['name']}
- **Tagline:** {post['tagline']}
- **Votes:** {post['votes']:,} | **Comments:** {post['comments']}
- **Topics:** {', '.join(post['topics'][:3]) if post['topics'] else 'N/A'}
- **Maker:** {post['maker'] or 'Unknown'} | **Hunter:** {post['hunter'] or 'Unknown'}
- **Link:** [View on PH]({post['url']}) | **Website:** [{post['website']}]({post['website']})

"""
        
        report += "## Categories\n\n"
        for category, cat_posts in list(categories.items())[:10]:
            avg_votes = sum(p['votes'] for p in cat_posts) / len(cat_posts)
            report += f"- **{category}:** {len(cat_posts)} products (avg {avg_votes:.0f} votes)\n"
        
        report += "\n---\n*Generated by Product Hunt Launch Tracker*\n"
        return report
    
    def save_report(self, report):
        os.makedirs('reports', exist_ok=True)
        date_str = datetime.now().strftime('%Y-%m-%d')
        filename = f'reports/producthunt-report-{date_str}.md'
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(report)
        print(f"Report saved: {filename}")
        return filename
    
    def send_slack_notification(self, posts):
        if not self.slack_webhook:
            return
        top_5 = posts[:5]
        blocks = [
            {"type": "header", "text": {"type": "plain_text", "text": f"PH Report - {datetime.now().strftime('%Y-%m-%d')}"}},
            {"type": "section", "text": {"type": "mrkdwn", "text": f"*Products:* {len(posts)} | *Votes:* {sum(p['votes'] for p in posts):,}"}},
            {"type": "divider"}
        ]
        for post in top_5:
            blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": f"*<{post['url']}|{post['name']}>*\n{post['tagline']}\n{post['votes']:,} votes | {post['comments']} comments"}})
        try:
            requests.post(self.slack_webhook, json={"blocks": blocks}, timeout=10)
            print("Slack sent")
        except Exception as e:
            print(f"Slack error: {e}")
    
    def send_telegram_notification(self, posts):
        if not self.telegram_token or not self.telegram_chat_id:
            return
        top_5 = posts[:5]
        message = f"<b>Product Hunt Report</b>\n{datetime.now().strftime('%Y-%m-%d')}\n\n"
        message += f"Products: {len(posts)} | Votes: {sum(p['votes'] for p in posts):,}\n\n<b>Top 5:</b>\n\n"
        for i, post in enumerate(top_5, 1):
            tagline = post['tagline'][:80] + "..." if len(post['tagline']) > 80 else post['tagline']
            message += f"{i}. <a href='{post['url']}'>{post['name']}</a>\n{post['votes']:,} votes | {tagline}\n\n"
        try:
            url = f"https://api.telegram.org/bot{self.telegram_token}/sendMessage"
            requests.post(url, json={"chat_id": self.telegram_chat_id, "text": message, "parse_mode": "HTML", "disable_web_page_preview": True}, timeout=10)
            print("Telegram sent")
        except Exception as e:
            print(f"Telegram error: {e}")

def main():
    print("Starting Product Hunt Tracker...")
    tracker = ProductHuntTracker()
    posts = tracker.fetch_today_posts(limit=20)
    
    if not posts:
        print("No posts fetched. Check your API token.")
        return
    
    print(f"Fetched {len(posts)} posts")
    report = tracker.generate_report(posts)
    tracker.save_report(report)
    tracker.send_slack_notification(posts)
    tracker.send_telegram_notification(posts)
    print("Done!")

if __name__ == "__main__":
    main()
